### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by zyunzh** [DependableSystemsLab/eTainter#1]
I got such a problem as follows when i ran the command "python bin/analyzer.py -f runningExample.code -b -m 8". And i don't know that's why.
Traceback (most recent call last):
  File "/mnt/hgfs/vm_share/eTainter-main/eTainter-main/bin/analyzer.py", line 12, in <module>
    from src.project import Project
  File "/mnt/hgfs/vm_share/eTainter-main/eTainter-main/src/__init__.py", line 11, in <module>
    from . import storage
ImportError: cannot import name 'storage' from partially initialized module 'src' (most likely due to a circular import) (/mnt/hgfs/vm_share/eTainter-main/eTainter-main/src/__init__.py)

**Comment by AsemGhaleb** [comment]
Try to re pull and run the command. The issue should be fixed.

**Comment by zyunzh** [comment]
> Try to re pull and run the command. The issue should be fixed.
What do you mean by “re pull”. May i know how to do with it？

**Comment by AsemGhaleb** [comment]
I mean, we have updated the code to fix the issue. So, please clone the code again to get updated code.
