### ISSUE TITLE
annotated_bugs.csv

### ISSUE THREAD

**Issue by zyunzh** [DependableSystemsLab/eTainter#2]
When I looked at the file "datasets/annotated/annotated_bugs.csv", I found that some contracts did not have any tags behind them, such as "543b20a73697fb0dc168871faa02b574"; some contracts had zero bugs, but their functions and locations were marked, such as "f0848d72cdcfe42fffad227f02759eb9". That is why? Could you give me a dataset that is manually marked with vulnerabilities? Thank you!

**Comment by AsemGhaleb** [comment]
File updated. Contracts with no corresponding tags have no bugs annotated

**Comment by AsemGhaleb** [comment]
File updated. Contracts with no corresponding tags have no bugs annotated
